from __future__ import annotations


# These snapshots are the concrete team shells the current M-A field keeps
# returning to in May 2026 tournament-result tracking. They intentionally sit
# one layer below the broader mode snapshots so the analyzer can surface real
# teams, their defining cores, and the Pokemon repeatedly attached to those
# results. `field_relevance` controls whether a shell is meta-board worthy:
# core, established, and rising teams stay user-facing, while fringe and deep
# cut shells can remain curated here without being presented as central field
# pillars.
TOURNAMENT_TEAM_SNAPSHOTS = (
    {
        "slug": "mega-gardevoir-tailroom",
        "label": "Mega Gardevoir Tailroom",
        "source": "Live May 2026 M-A tournament snapshot",
        "result_label": "recent top cut",
        "field_relevance": 0.82,
        "popularity_weight": 0.62,
        "result_weight": 0.82,
        "modes": ("tailroom", "trick_room", "tailwind"),
        "mode_weights": {"tailroom": 0.5, "trick_room": 0.3, "tailwind": 0.2},
        "broad_mix": {"balance": 0.45, "bulky_offense": 0.35, "trick_room": 0.2},
        "key_pokemon": ("gardevoir-mega", "whimsicott", "sneasler", "kingambit", "primarina"),
        "key_cores": ("Gardevoir-Mega + Whimsicott", "Sneasler + Kingambit"),
    },
    {
        "slug": "mega-scizor-balance",
        "label": "Mega Scizor Balance",
        "source": "Live May 2026 M-A tournament snapshot",
        "result_label": "recent top cut",
        "field_relevance": 0.78,
        "popularity_weight": 0.58,
        "result_weight": 0.79,
        "modes": ("tailwind", "tailroom", "trick_room"),
        "mode_weights": {"tailwind": 0.45, "tailroom": 0.3, "trick_room": 0.25},
        "broad_mix": {"balance": 0.55, "bulky_offense": 0.35, "trick_room": 0.1},
        "key_pokemon": ("scizor-mega", "sneasler", "garchomp", "aerodactyl", "sinistcha", "milotic"),
        "key_cores": ("Sneasler + Scizor-Mega", "Garchomp + Aerodactyl"),
    },
    {
        "slug": "rain-archaludon",
        "label": "Rain Archaludon",
        "source": "Repeated May 2026 M-A top-cut shell",
        "result_label": "multiple top cuts",
        "field_relevance": 1.0,
        "popularity_weight": 0.92,
        "result_weight": 0.94,
        "modes": ("rain_tailwind", "rain"),
        "mode_weights": {"rain_tailwind": 0.7, "rain": 0.3},
        "broad_mix": {"bulky_offense": 0.55, "balance": 0.25, "hyper_offense": 0.2},
        "key_pokemon": ("pelipper", "archaludon", "basculegion", "sinistcha", "incineroar", "scizor"),
        "key_cores": ("Pelipper + Archaludon", "Archaludon + Basculegion"),
    },
    {
        "slug": "mega-charizard-y-aerodactyl",
        "label": "Mega Charizard Y Aerodactyl",
        "source": "Recent May 2026 M-A tournament front-runner",
        "result_label": "top-table finish",
        "field_relevance": 1.0,
        "popularity_weight": 0.96,
        "result_weight": 0.95,
        "modes": ("sun_tailwind", "tailwind", "sun"),
        "mode_weights": {"sun_tailwind": 0.45, "tailwind": 0.4, "sun": 0.15},
        "broad_mix": {"hyper_offense": 0.62, "bulky_offense": 0.38},
        "key_pokemon": ("charizard-mega-y", "aerodactyl", "sylveon", "garchomp", "kingambit", "basculegion"),
        "key_cores": ("Mega Charizard Y + Aerodactyl", "Garchomp + Basculegion"),
    },
    {
        "slug": "mega-glimmora-offense",
        "label": "Mega Glimmora Offense",
        "source": "Recent May 2026 M-A high-result shell",
        "result_label": "recent strong finishes",
        "field_relevance": 0.72,
        "popularity_weight": 0.54,
        "result_weight": 0.77,
        "modes": ("tailwind",),
        "mode_weights": {"tailwind": 1.0},
        "broad_mix": {"hyper_offense": 0.72, "bulky_offense": 0.28},
        "key_pokemon": ("glimmora-mega", "aerodactyl", "garchomp", "kingambit", "sneasler", "basculegion"),
        "key_cores": ("Mega Glimmora + Aerodactyl", "Mega Glimmora + Garchomp"),
    },
    {
        "slug": "farigiraf-torkoal-room",
        "label": "Farigiraf Torkoal Room",
        "source": "Repeated May 2026 M-A top-cut shell",
        "result_label": "repeated deep runs",
        "field_relevance": 0.88,
        "popularity_weight": 0.84,
        "result_weight": 0.91,
        "modes": ("trick_room", "sun_room"),
        "mode_weights": {"trick_room": 0.65, "sun_room": 0.35},
        "broad_mix": {"trick_room": 0.65, "bulky_offense": 0.2, "balance": 0.15},
        "key_pokemon": ("farigiraf", "torkoal", "sinistcha", "kangaskhan", "hatterene", "aegislash"),
        "key_cores": ("Farigiraf + Torkoal", "Farigiraf + Sinistcha"),
    },
    {
        "slug": "sand-garchomp-balance",
        "label": "Sand Garchomp Balance",
        "source": "Repeated May 2026 M-A tournament shell",
        "result_label": "repeated day two",
        "field_relevance": 0.48,
        "popularity_weight": 0.46,
        "result_weight": 0.68,
        "modes": ("sand", "sand_tailwind"),
        "mode_weights": {"sand": 0.55, "sand_tailwind": 0.45},
        "broad_mix": {"balance": 0.4, "bulky_offense": 0.4, "hyper_offense": 0.2},
        "key_pokemon": ("tyranitar", "garchomp", "corviknight", "scizor-mega", "sinistcha", "milotic"),
        "key_cores": ("Tyranitar + Garchomp", "Corviknight + Garchomp"),
    },
    {
        "slug": "hydrapple-grassy-balance",
        "label": "Hydrapple Grassy Balance",
        "source": "Repeated May 2026 M-A tournament shell",
        "result_label": "recent deep cut",
        "field_relevance": 0.36,
        "popularity_weight": 0.4,
        "result_weight": 0.65,
        "modes": ("grassy_terrain",),
        "mode_weights": {"grassy_terrain": 1.0},
        "broad_mix": {"balance": 0.45, "bulky_offense": 0.25, "semi_stall": 0.3},
        "key_pokemon": ("hydrapple", "sinistcha", "venusaur", "torterra", "roserade", "whimsicott"),
        "key_cores": ("Hydrapple + Sinistcha", "Hydrapple + Venusaur"),
    },
    {
        "slug": "ninetales-snow-room",
        "label": "Ninetales-A Snow Room",
        "source": "Repeated May 2026 M-A tournament shell",
        "result_label": "recent deep cut",
        "field_relevance": 0.3,
        "popularity_weight": 0.34,
        "result_weight": 0.61,
        "modes": ("snow_room", "snow"),
        "mode_weights": {"snow_room": 0.65, "snow": 0.35},
        "broad_mix": {"trick_room": 0.45, "balance": 0.25, "bulky_offense": 0.3},
        "key_pokemon": ("ninetales-alola", "farigiraf", "sinistcha", "primarina", "kingambit", "abomasnow"),
        "key_cores": ("Ninetales-A + Farigiraf", "Ninetales-A + Sinistcha"),
    },
)