from __future__ import annotations


MODE_LABEL_ORDER = (
    "tailwind",
    "trick_room",
    "semiroom",
    "tailroom",
    "dual_mode",
    "rain",
    "sun",
    "sand",
    "snow",
    "electric_terrain",
    "grassy_terrain",
    "misty_terrain",
    "psychic_terrain",
    "rain_tailwind",
    "sun_tailwind",
    "sand_tailwind",
    "snow_tailwind",
    "rain_room",
    "sun_room",
    "sand_room",
    "snow_room",
    "rain_tailroom",
    "sun_tailroom",
)

# Curated from ChampionsMeta Regulation M-A tournament pages and the recent
# 100+ player tournament-team snapshots surfaced in May 2026. The weights are
# intentionally qualitative: they bias the analyzer toward the most repeated
# Regulation M-A modes without pretending to be a perfect statistical export.
# This list now covers the analyzer's full current mode-shell taxonomy; broad
# styles and endgame packages still live in separate layers.
TOURNAMENT_MODE_SNAPSHOTS = {
    "tailwind": {
        "broad_mix": {"hyper_offense": 0.7, "bulky_offense": 0.3},
        "tournament_weight": 1.0,
        "required_features": ("tailwind",),
        "identity_feature_weights": {
            "tailwind": 1.5,
            "tailwind_shell": 0.08,
            "speed_control": 0.08,
            "pressure": 0.12,
        },
        "counterplay_feature_weights": {"tailwind_counterplay": 0.55, "priority": 0.12, "screens": 0.1},
        "pressure_types": {"ground": 1.3, "water": 1.0, "ghost": 1.0, "rock": 0.9, "dark": 0.8, "fire": 0.8},
        "exposure_weight": 0.55,
        "signature_species": {
            "charizard": 0.9,
            "garchomp": 0.9,
            "basculegion": 0.8,
            "kingambit": 0.8,
            "aerodactyl": 0.8,
            "whimsicott": 0.7,
            "glimmora": 0.5,
            "sneasler": 0.5,
        },
    },
    "rain": {
        "broad_mix": {"bulky_offense": 0.5, "balance": 0.3, "hyper_offense": 0.2},
        "tournament_weight": 0.42,
        "required_features": ("rain",),
        "identity_feature_weights": {"rain": 1.35, "rain_shell": 0.08, "resilience": 0.08, "pressure": 0.06},
        "counterplay_feature_weights": {"weather_counterplay": 0.5, "rain_punish_coverage": 0.18},
        "pressure_types": {"water": 1.35, "ghost": 0.85, "dragon": 0.8, "steel": 0.6},
        "exposure_weight": 0.58,
        "signature_species": {
            "pelipper": 1.0,
            "politoed": 0.9,
            "archaludon": 0.85,
            "basculegion": 0.8,
            "sinistcha": 0.45,
            "incineroar": 0.35,
        },
    },
    "rain_tailwind": {
        "broad_mix": {"hyper_offense": 0.35, "bulky_offense": 0.45, "balance": 0.2},
        "tournament_weight": 0.82,
        "required_features": ("rain", "tailwind"),
        "identity_feature_weights": {
            "rain": 1.2,
            "tailwind": 1.1,
            "rain_tailwind_shell": 0.1,
            "pressure": 0.08,
            "resilience": 0.08,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.45,
            "tailwind_counterplay": 0.35,
            "rain_punish_coverage": 0.18,
            "wide_guard": 0.08,
        },
        "pressure_types": {"water": 1.35, "dragon": 0.9, "steel": 0.7, "electric": 0.6, "ghost": 0.6},
        "exposure_weight": 0.62,
        "signature_species": {
            "pelipper": 1.0,
            "archaludon": 0.95,
            "basculegion": 0.9,
            "sinistcha": 0.6,
            "incineroar": 0.5,
            "scizor": 0.45,
            "sneasler": 0.45,
            "dragonite": 0.35,
        },
    },
    "trick_room": {
        "broad_mix": {"trick_room": 0.8, "bulky_offense": 0.2},
        "tournament_weight": 0.7,
        "required_features": ("trick_room",),
        "identity_feature_weights": {
            "trick_room": 1.6,
            "trick_room_shell": 0.1,
            "resilience": 0.1,
            "redirection": 0.25,
        },
        "counterplay_feature_weights": {"trick_room_counterplay": 0.65, "priority": 0.12, "wide_guard": 0.1},
        "pressure_types": {"fire": 1.1, "ghost": 1.0, "fairy": 0.9, "ground": 0.8, "water": 0.7, "dark": 0.6},
        "exposure_weight": 0.6,
        "signature_species": {
            "farigiraf": 1.0,
            "sinistcha": 0.9,
            "incineroar": 0.65,
            "torkoal": 0.7,
            "kangaskhan": 0.6,
            "basculegion": 0.55,
            "aegislash": 0.5,
            "hatterene": 0.5,
            "gengar": 0.45,
            "politoed": 0.35,
        },
    },
    "tailroom": {
        "broad_mix": {"hyper_offense": 0.35, "trick_room": 0.35, "balance": 0.3},
        "tournament_weight": 0.64,
        "required_features": ("tailwind", "trick_room"),
        "identity_feature_weights": {
            "tailwind": 1.0,
            "trick_room": 1.0,
            "tailroom_shell": 0.1,
            "speed_control": 0.1,
            "resilience": 0.08,
        },
        "counterplay_feature_weights": {"tailwind_counterplay": 0.28, "trick_room_counterplay": 0.45, "priority": 0.08},
        "pressure_types": {"ground": 1.1, "water": 0.8, "ghost": 0.8, "fairy": 0.8, "fire": 0.7},
        "exposure_weight": 0.55,
        "signature_species": {
            "charizard": 0.8,
            "garchomp": 0.8,
            "farigiraf": 0.75,
            "basculegion": 0.7,
            "whimsicott": 0.6,
            "sylveon": 0.55,
            "sinistcha": 0.55,
            "aerodactyl": 0.45,
        },
    },
    "semiroom": {
        "broad_mix": {"balance": 0.35, "trick_room": 0.35, "bulky_offense": 0.3},
        "tournament_weight": 0.26,
        "required_features": ("trick_room",),
        "identity_feature_weights": {
            "trick_room": 1.0,
            "semiroom_shell": 0.14,
            "resilience": 0.1,
            "speed_control": 0.08,
            "pressure": 0.04,
        },
        "counterplay_feature_weights": {"trick_room_counterplay": 0.45, "priority": 0.08, "wide_guard": 0.06},
        "pressure_types": {"ground": 0.9, "fire": 0.8, "fairy": 0.8, "ghost": 0.7, "water": 0.6},
        "exposure_weight": 0.58,
        "signature_species": {
            "farigiraf": 0.9,
            "sinistcha": 0.85,
            "primarina": 0.55,
            "kingambit": 0.5,
            "corviknight": 0.35,
        },
    },
    "dual_mode": {
        "broad_mix": {"balance": 0.35, "bulky_offense": 0.35, "trick_room": 0.15, "hyper_offense": 0.15},
        "tournament_weight": 0.34,
        "required_features": (),
        "identity_feature_weights": {
            "dual_mode_shell": 0.16,
            "tailwind_shell": 0.06,
            "trick_room_shell": 0.06,
            "speed_control": 0.1,
            "resilience": 0.08,
            "pressure": 0.06,
        },
        "counterplay_feature_weights": {
            "tailwind_counterplay": 0.18,
            "trick_room_counterplay": 0.18,
            "weather_counterplay": 0.08,
            "priority": 0.06,
        },
        "pressure_types": {"ground": 0.9, "water": 0.9, "fire": 0.8, "ghost": 0.7, "fairy": 0.7},
        "exposure_weight": 0.57,
        "signature_species": {
            "farigiraf": 0.75,
            "aerodactyl": 0.7,
            "whimsicott": 0.6,
            "sinistcha": 0.6,
            "basculegion": 0.55,
            "torkoal": 0.45,
            "pelipper": 0.4,
        },
    },
    "electric_terrain": {
        "broad_mix": {"hyper_offense": 0.45, "bulky_offense": 0.35, "balance": 0.2},
        "tournament_weight": 0.12,
        "required_features": ("electric_terrain",),
        "identity_feature_weights": {
            "electric_terrain": 1.3,
            "electric_terrain_shell": 0.12,
            "pressure": 0.08,
            "speed_control": 0.06,
        },
        "counterplay_feature_weights": {"electric_punish_coverage": 0.34, "screens": 0.06, "priority": 0.05},
        "pressure_types": {"electric": 1.2, "water": 0.8, "flying": 0.8, "fairy": 0.7, "steel": 0.6},
        "exposure_weight": 0.55,
        "signature_species": {
            "raichu-alola": 0.9,
            "raichu": 0.8,
            "jolteon": 0.7,
            "rotom": 0.55,
            "ampharos": 0.45,
        },
    },
    "grassy_terrain": {
        "broad_mix": {"balance": 0.4, "bulky_offense": 0.35, "semi_stall": 0.25},
        "tournament_weight": 0.11,
        "required_features": ("grassy_terrain",),
        "identity_feature_weights": {
            "grassy_terrain": 1.2,
            "grassy_terrain_shell": 0.12,
            "resilience": 0.08,
            "pressure": 0.06,
            "healing_support": 0.08,
        },
        "counterplay_feature_weights": {"grass_punish_coverage": 0.28, "tailwind_counterplay": 0.08, "priority": 0.04},
        "pressure_types": {"grass": 1.1, "ground": 0.9, "water": 0.8, "rock": 0.7, "fire": 0.6},
        "exposure_weight": 0.57,
        "signature_species": {
            "hydrapple": 0.9,
            "venusaur": 0.8,
            "sinistcha": 0.8,
            "torterra": 0.7,
            "roserade": 0.55,
            "whimsicott": 0.4,
        },
    },
    "misty_terrain": {
        "broad_mix": {"balance": 0.4, "semi_stall": 0.3, "bulky_offense": 0.3},
        "tournament_weight": 0.09,
        "required_features": ("misty_terrain",),
        "identity_feature_weights": {
            "misty_terrain": 1.15,
            "misty_terrain_shell": 0.12,
            "resilience": 0.1,
            "healing_support": 0.12,
            "redirection": 0.08,
        },
        "counterplay_feature_weights": {"fairy_punish_coverage": 0.3, "screens": 0.05, "priority": 0.03},
        "pressure_types": {"fairy": 1.1, "water": 0.8, "grass": 0.7, "steel": 0.7},
        "exposure_weight": 0.58,
        "signature_species": {
            "primarina": 0.95,
            "florges": 0.85,
            "audino": 0.75,
            "sylveon": 0.65,
            "ninetales-alola": 0.4,
        },
    },
    "psychic_terrain": {
        "broad_mix": {"hyper_offense": 0.4, "bulky_offense": 0.2, "trick_room": 0.25, "balance": 0.15},
        "tournament_weight": 0.18,
        "required_features": ("psychic_terrain",),
        "identity_feature_weights": {
            "psychic_terrain": 1.2,
            "psychic_terrain_shell": 0.12,
            "expanding_force": 0.8,
            "pressure": 0.08,
            "redirection": 0.05,
        },
        "counterplay_feature_weights": {"psychic_punish_coverage": 0.32, "screens": 0.06, "trick_room_counterplay": 0.08},
        "pressure_types": {"psychic": 1.2, "fairy": 0.9, "fire": 0.8, "ground": 0.8, "dark": 0.6},
        "exposure_weight": 0.58,
        "signature_species": {
            "farigiraf": 0.85,
            "hatterene": 0.8,
            "armarouge": 0.75,
            "raichu-alola": 0.65,
            "gardevoir": 0.55,
            "slowking": 0.35,
        },
    },
    "rain_room": {
        "broad_mix": {"trick_room": 0.55, "bulky_offense": 0.25, "balance": 0.2},
        "tournament_weight": 0.48,
        "required_features": ("rain", "trick_room"),
        "identity_feature_weights": {
            "rain": 1.0,
            "trick_room": 1.1,
            "rain_room_shell": 0.1,
            "resilience": 0.1,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.25,
            "trick_room_counterplay": 0.5,
            "rain_punish_coverage": 0.12,
            "wide_guard": 0.1,
        },
        "pressure_types": {"water": 1.1, "ghost": 1.0, "fire": 0.9, "fairy": 0.8, "steel": 0.6},
        "exposure_weight": 0.6,
        "signature_species": {
            "gengar": 0.95,
            "politoed": 0.95,
            "sinistcha": 0.9,
            "incineroar": 0.7,
            "archaludon": 0.55,
            "basculegion": 0.5,
            "snorlax": 0.45,
            "hawlucha": 0.35,
        },
    },
    "rain_tailroom": {
        "broad_mix": {"hyper_offense": 0.2, "bulky_offense": 0.3, "trick_room": 0.3, "balance": 0.2},
        "tournament_weight": 0.36,
        "required_features": ("rain", "tailwind", "trick_room"),
        "identity_feature_weights": {
            "rain": 0.9,
            "tailwind": 0.9,
            "trick_room": 0.9,
            "rain_tailroom_shell": 0.12,
            "resilience": 0.06,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.22,
            "tailwind_counterplay": 0.25,
            "trick_room_counterplay": 0.32,
            "wide_guard": 0.08,
        },
        "pressure_types": {"water": 1.2, "dragon": 0.8, "ghost": 0.8, "fairy": 0.7},
        "exposure_weight": 0.62,
        "signature_species": {
            "pelipper": 1.0,
            "basculegion": 0.95,
            "sinistcha": 0.9,
            "archaludon": 0.85,
            "sableye": 0.55,
            "dragonite": 0.45,
            "farigiraf": 0.35,
        },
    },
    "sand": {
        "broad_mix": {"bulky_offense": 0.45, "balance": 0.35, "hyper_offense": 0.2},
        "tournament_weight": 0.36,
        "required_features": ("sand",),
        "identity_feature_weights": {"sand": 1.3, "sand_shell": 0.08, "pressure": 0.08, "resilience": 0.08},
        "counterplay_feature_weights": {"weather_counterplay": 0.2, "sand_punish_coverage": 0.25, "priority": 0.06, "tailwind_counterplay": 0.1},
        "pressure_types": {"ground": 1.2, "rock": 1.0, "steel": 0.8, "dragon": 0.6, "dark": 0.5},
        "exposure_weight": 0.56,
        "signature_species": {
            "tyranitar": 1.0,
            "excadrill": 1.0,
            "hippowdon": 0.75,
            "rhyperior": 0.65,
            "garchomp": 0.7,
            "milotic": 0.4,
            "corviknight": 0.4,
            "rotom": 0.35,
            "sinistcha": 0.3,
        },
    },
    "snow": {
        "broad_mix": {"balance": 0.35, "bulky_offense": 0.35, "hyper_offense": 0.3},
        "tournament_weight": 0.18,
        "required_features": ("snow",),
        "identity_feature_weights": {"snow": 1.3, "snow_shell": 0.08, "resilience": 0.08},
        "counterplay_feature_weights": {"weather_counterplay": 0.12, "snow_punish_coverage": 0.25},
        "pressure_types": {"ice": 1.1, "fairy": 0.8, "ground": 0.7},
        "exposure_weight": 0.57,
        "signature_species": {
            "ninetales-alola": 1.0,
            "rotom-wash": 0.5,
            "garchomp": 0.45,
            "incineroar": 0.35,
            "kangaskhan": 0.35,
            "abomasnow": 0.4,
            "basculegion": 0.3,
        },
    },
    "snow_tailwind": {
        "broad_mix": {"hyper_offense": 0.4, "bulky_offense": 0.35, "balance": 0.25},
        "tournament_weight": 0.31,
        "required_features": ("snow", "tailwind"),
        "identity_feature_weights": {
            "snow": 1.1,
            "tailwind": 1.0,
            "snow_tailwind_shell": 0.1,
            "speed_control": 0.08,
        },
        "counterplay_feature_weights": {"tailwind_counterplay": 0.32, "weather_counterplay": 0.12, "snow_punish_coverage": 0.24, "priority": 0.06},
        "pressure_types": {"ice": 1.2, "fairy": 0.9, "ground": 0.8, "water": 0.7, "rock": 0.6},
        "exposure_weight": 0.58,
        "signature_species": {
            "ninetales-alola": 1.0,
            "garchomp": 0.7,
            "rotom-wash": 0.5,
            "aerodactyl": 0.45,
            "scizor": 0.45,
            "basculegion": 0.45,
            "talonflame": 0.35,
        },
    },
    "sun": {
        "broad_mix": {"bulky_offense": 0.45, "hyper_offense": 0.35, "balance": 0.2},
        "tournament_weight": 0.16,
        "required_features": ("sun",),
        "identity_feature_weights": {"sun": 1.25, "sun_shell": 0.08, "pressure": 0.08},
        "counterplay_feature_weights": {"weather_counterplay": 0.15, "sun_punish_coverage": 0.24},
        "pressure_types": {"fire": 1.2, "grass": 0.8, "ground": 0.7, "rock": 0.7},
        "exposure_weight": 0.58,
        "signature_species": {
            "charizard": 0.9,
            "venusaur": 0.8,
            "torkoal": 0.7,
            "incineroar": 0.4,
            "sneasler": 0.35,
            "basculegion": 0.25,
        },
    },
    "sun_tailwind": {
        "broad_mix": {"hyper_offense": 0.4, "bulky_offense": 0.4, "balance": 0.2},
        "tournament_weight": 0.24,
        "required_features": ("sun", "tailwind"),
        "identity_feature_weights": {
            "sun": 1.05,
            "tailwind": 1.0,
            "sun_tailwind_shell": 0.12,
            "pressure": 0.08,
            "speed_control": 0.07,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.18,
            "tailwind_counterplay": 0.3,
            "sun_punish_coverage": 0.2,
            "wide_guard": 0.06,
        },
        "pressure_types": {"fire": 1.2, "grass": 0.9, "ground": 0.8, "rock": 0.7, "flying": 0.6},
        "exposure_weight": 0.59,
        "signature_species": {
            "charizard": 1.0,
            "venusaur": 0.9,
            "torkoal": 0.7,
            "talonflame": 0.55,
            "aerodactyl": 0.55,
            "whimsicott": 0.45,
        },
    },
    "sand_tailwind": {
        "broad_mix": {"bulky_offense": 0.45, "hyper_offense": 0.35, "balance": 0.2},
        "tournament_weight": 0.22,
        "required_features": ("sand", "tailwind"),
        "identity_feature_weights": {
            "sand": 1.0,
            "tailwind": 1.0,
            "sand_tailwind_shell": 0.12,
            "pressure": 0.08,
            "speed_control": 0.06,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.14,
            "tailwind_counterplay": 0.28,
            "sand_punish_coverage": 0.22,
            "priority": 0.05,
        },
        "pressure_types": {"ground": 1.2, "rock": 1.0, "steel": 0.8, "dragon": 0.6, "dark": 0.5},
        "exposure_weight": 0.58,
        "signature_species": {
            "tyranitar": 1.0,
            "garchomp": 0.8,
            "corviknight": 0.65,
            "aerodactyl": 0.6,
            "excadrill": 0.55,
            "hippowdon": 0.45,
        },
    },
    "sun_room": {
        "broad_mix": {"trick_room": 0.5, "bulky_offense": 0.25, "hyper_offense": 0.25},
        "tournament_weight": 0.28,
        "required_features": ("sun", "trick_room"),
        "identity_feature_weights": {
            "sun": 1.1,
            "trick_room": 1.1,
            "sun_room_shell": 0.1,
            "pressure": 0.08,
        },
        "counterplay_feature_weights": {"weather_counterplay": 0.15, "trick_room_counterplay": 0.42, "sun_punish_coverage": 0.22, "wide_guard": 0.08},
        "pressure_types": {"fire": 1.2, "ground": 0.9, "fairy": 0.8, "rock": 0.8, "grass": 0.6},
        "exposure_weight": 0.6,
        "signature_species": {
            "torkoal": 1.0,
            "farigiraf": 0.9,
            "charizard": 0.75,
            "sinistcha": 0.6,
            "kingambit": 0.4,
            "sylveon": 0.4,
            "kangaskhan": 0.35,
        },
    },
    "sand_room": {
        "broad_mix": {"trick_room": 0.45, "bulky_offense": 0.3, "balance": 0.25},
        "tournament_weight": 0.18,
        "required_features": ("sand", "trick_room"),
        "identity_feature_weights": {
            "sand": 1.0,
            "trick_room": 1.0,
            "sand_room_shell": 0.14,
            "resilience": 0.08,
            "pressure": 0.06,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.12,
            "trick_room_counterplay": 0.42,
            "sand_punish_coverage": 0.22,
            "wide_guard": 0.06,
        },
        "pressure_types": {"ground": 1.2, "rock": 1.0, "steel": 0.8, "fire": 0.7, "dark": 0.6},
        "exposure_weight": 0.6,
        "signature_species": {
            "tyranitar": 1.0,
            "hippowdon": 0.9,
            "farigiraf": 0.8,
            "sinistcha": 0.75,
            "rhyperior": 0.7,
            "kingambit": 0.5,
            "garchomp": 0.45,
        },
    },
    "snow_room": {
        "broad_mix": {"trick_room": 0.45, "balance": 0.3, "bulky_offense": 0.25},
        "tournament_weight": 0.14,
        "required_features": ("snow", "trick_room"),
        "identity_feature_weights": {
            "snow": 1.0,
            "trick_room": 1.0,
            "snow_room_shell": 0.14,
            "resilience": 0.08,
            "screens": 0.08,
            "redirection": 0.05,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.1,
            "trick_room_counterplay": 0.4,
            "snow_punish_coverage": 0.22,
            "wide_guard": 0.06,
        },
        "pressure_types": {"ice": 1.2, "ground": 0.9, "fairy": 0.8, "fire": 0.8, "steel": 0.7},
        "exposure_weight": 0.6,
        "signature_species": {
            "ninetales-alola": 1.0,
            "abomasnow": 0.8,
            "farigiraf": 0.75,
            "sinistcha": 0.7,
            "kingambit": 0.5,
            "primarina": 0.45,
        },
    },
    "sun_tailroom": {
        "broad_mix": {"hyper_offense": 0.2, "bulky_offense": 0.25, "trick_room": 0.3, "balance": 0.25},
        "tournament_weight": 0.22,
        "required_features": ("sun", "tailwind", "trick_room"),
        "identity_feature_weights": {
            "sun": 0.9,
            "tailwind": 0.9,
            "trick_room": 0.9,
            "sun_tailroom_shell": 0.14,
            "resilience": 0.06,
        },
        "counterplay_feature_weights": {
            "weather_counterplay": 0.14,
            "tailwind_counterplay": 0.22,
            "trick_room_counterplay": 0.28,
            "sun_punish_coverage": 0.18,
            "wide_guard": 0.06,
        },
        "pressure_types": {"fire": 1.2, "ground": 0.9, "fairy": 0.8, "rock": 0.8, "grass": 0.6},
        "exposure_weight": 0.61,
        "signature_species": {
            "torkoal": 1.0,
            "farigiraf": 0.9,
            "charizard": 0.75,
            "aerodactyl": 0.65,
            "sableye": 0.55,
            "venusaur": 0.45,
            "kingambit": 0.4,
        },
    },
}