from __future__ import annotations


ELIGIBLE_SPECIES = (
    "Venusaur",
    "Charizard",
    "Blastoise",
    "Beedrill",
    "Pidgeot",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Raichu (Alolan Form)",
    "Clefable",
    "Ninetales",
    "Ninetales (Alolan Form)",
    "Arcanine",
    "Arcanine (Hisuian Form)",
    "Alakazam",
    "Machamp",
    "Victreebel",
    "Slowbro",
    "Slowbro (Galarian Form)",
    "Gengar",
    "Kangaskhan",
    "Starmie",
    "Pinsir",
    "Tauros",
    "Tauros (Paldean Form (Combat Breed))",
    "Tauros (Paldean Form (Blaze Breed))",
    "Tauros (Paldean Form (Aqua Breed))",
    "Gyarados",
    "Ditto",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Aerodactyl",
    "Snorlax",
    "Dragonite",
    "Meganium",
    "Typhlosion",
    "Typhlosion (Hisuian Form)",
    "Feraligatr",
    "Ariados",
    "Ampharos",
    "Azumarill",
    "Politoed",
    "Espeon",
    "Umbreon",
    "Slowking",
    "Slowking (Galarian Form)",
    "Forretress",
    "Steelix",
    "Scizor",
    "Heracross",
    "Skarmory",
    "Houndoom",
    "Tyranitar",
    "Pelipper",
    "Gardevoir",
    "Sableye",
    "Aggron",
    "Medicham",
    "Manectric",
    "Sharpedo",
    "Camerupt",
    "Torkoal",
    "Altaria",
    "Milotic",
    "Castform",
    "Banette",
    "Chimecho",
    "Absol",
    "Glalie",
    "Torterra",
    "Infernape",
    "Empoleon",
    "Luxray",
    "Roserade",
    "Rampardos",
    "Bastiodon",
    "Lopunny",
    "Spiritomb",
    "Garchomp",
    "Lucario",
    "Hippowdon",
    "Toxicroak",
    "Abomasnow",
    "Weavile",
    "Rhyperior",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Gallade",
    "Froslass",
    "Rotom (Rotom)",
    "Rotom (Heat Rotom)",
    "Rotom (Wash Rotom)",
    "Rotom (Frost Rotom)",
    "Rotom (Fan Rotom)",
    "Rotom (Mow Rotom)",
    "Serperior",
    "Emboar",
    "Samurott",
    "Samurott (Hisuian Form)",
    "Watchog",
    "Liepard",
    "Simisage",
    "Simisear",
    "Simipour",
    "Excadrill",
    "Audino",
    "Conkeldurr",
    "Whimsicott",
    "Krookodile",
    "Cofagrigus",
    "Garbodor",
    "Zoroark",
    "Zoroark (Hisuian Form)",
    "Reuniclus",
    "Vanilluxe",
    "Emolga",
    "Chandelure",
    "Beartic",
    "Stunfisk",
    "Stunfisk (Galarian Form)",
    "Golurk",
    "Hydreigon",
    "Volcarona",
    "Chesnaught",
    "Delphox",
    "Greninja",
    "Diggersby",
    "Talonflame",
    "Vivillon",
    "Eternal Flower Floette",
    "Florges",
    "Pangoro",
    "Furfrou",
    "Meowstic (Male)",
    "Meowstic (Female)",
    "Aegislash",
    "Aromatisse",
    "Slurpuff",
    "Clawitzer",
    "Heliolisk",
    "Tyrantrum",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Goodra",
    "Goodra (Hisuian Form)",
    "Klefki",
    "Trevenant",
    "Gourgeist (Medium Variety)",
    "Gourgeist (Small Variety)",
    "Gourgeist (Large Variety)",
    "Gourgeist (Jumbo Variety)",
    "Avalugg",
    "Avalugg (Hisuian Form)",
    "Noivern",
    "Decidueye",
    "Decidueye (Hisuian Form)",
    "Incineroar",
    "Primarina",
    "Toucannon",
    "Crabominable",
    "Lycanroc (Midday Form)",
    "Lycanroc (Midnight Form)",
    "Lycanroc (Dusk Form)",
    "Toxapex",
    "Mudsdale",
    "Araquanid",
    "Salazzle",
    "Tsareena",
    "Oranguru",
    "Passimian",
    "Mimikyu",
    "Drampa",
    "Kommo-o",
    "Corviknight",
    "Flapple",
    "Appletun",
    "Sandaconda",
    "Polteageist",
    "Hatterene",
    "Mr. Rime",
    "Runerigus",
    "Alcremie",
    "Morpeko",
    "Dragapult",
    "Wyrdeer",
    "Kleavor",
    "Basculegion (Male)",
    "Basculegion (Female)",
    "Sneasler",
    "Meowscarada",
    "Skeledirge",
    "Quaquaval",
    "Maushold",
    "Garganacl",
    "Armarouge",
    "Ceruledge",
    "Bellibolt",
    "Scovillain",
    "Espathra",
    "Tinkaton",
    "Palafin",
    "Orthworm",
    "Glimmora",
    "Farigiraf",
    "Kingambit",
    "Sinistcha",
    "Archaludon",
    "Hydrapple",
)

ALLOWED_MEGA_EVOLUTIONS = (
    "Mega Venusaur",
    "Mega Charizard X",
    "Mega Charizard Y",
    "Mega Blastoise",
    "Mega Beedrill",
    "Mega Pidgeot",
    "Mega Clefable",
    "Mega Alakazam",
    "Mega Victreebel",
    "Mega Slowbro",
    "Mega Gengar",
    "Mega Kangaskhan",
    "Mega Starmie",
    "Mega Pinsir",
    "Mega Gyarados",
    "Mega Aerodactyl",
    "Mega Dragonite",
    "Mega Meganium",
    "Mega Feraligatr",
    "Mega Ampharos",
    "Mega Steelix",
    "Mega Scizor",
    "Mega Heracross",
    "Mega Skarmory",
    "Mega Houndoom",
    "Mega Tyranitar",
    "Mega Gardevoir",
    "Mega Sableye",
    "Mega Aggron",
    "Mega Medicham",
    "Mega Manectric",
    "Mega Sharpedo",
    "Mega Camerupt",
    "Mega Altaria",
    "Mega Banette",
    "Mega Chimecho",
    "Mega Absol",
    "Mega Glalie",
    "Mega Lopunny",
    "Mega Garchomp",
    "Mega Lucario",
    "Mega Abomasnow",
    "Mega Gallade",
    "Mega Froslass",
    "Mega Emboar",
    "Mega Excadrill",
    "Mega Audino",
    "Mega Chandelure",
    "Mega Golurk",
    "Mega Chesnaught",
    "Mega Delphox",
    "Mega Greninja",
    "Mega Eternal Flower Floette",
    "Mega Meowstic",
    "Mega Hawlucha",
    "Mega Crabominable",
    "Mega Drampa",
    "Mega Scovillain",
    "Mega Glimmora",
)

ALLOWED_HELD_ITEMS = (
    "Black Belt",
    "Black Glasses",
    "Bright Powder",
    "Charcoal",
    "Choice Scarf",
    "Dragon Fang",
    "Fairy Feather",
    "Focus Band",
    "Focus Sash",
    "Hard Stone",
    "King's Rock",
    "Leftovers",
    "Light Ball",
    "Magnet",
    "Mental Herb",
    "Metal Coat",
    "Miracle Seed",
    "Mystic Water",
    "Never-Melt Ice",
    "Poison Barb",
    "Quick Claw",
    "Scope Lens",
    "Sharp Beak",
    "Shell Bell",
    "Silk Scarf",
    "Silver Powder",
    "Soft Sand",
    "Spell Tag",
    "Twisted Spoon",
    "White Herb",
    "Abomasite",
    "Absolite",
    "Aerodactylite",
    "Aggronite",
    "Alakazite",
    "Altarianite",
    "Ampharosite",
    "Audinite",
    "Banettite",
    "Beedrillite",
    "Blastoisinite",
    "Cameruptite",
    "Chandelurite",
    "Charizardite X",
    "Charizardite Y",
    "Chesnaughtite",
    "Chimechite",
    "Clefablite",
    "Crabominite",
    "Delphoxite",
    "Dragoninite",
    "Drampanite",
    "Emboarite",
    "Excadrite",
    "Feraligite",
    "Floettite",
    "Froslassite",
    "Galladite",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Glalitite",
    "Glimmoranite",
    "Golurkite",
    "Greninjite",
    "Gyaradosite",
    "Hawluchanite",
    "Heracronite",
    "Houndoominite",
    "Kangaskhanite",
    "Lopunnite",
    "Lucarionite",
    "Manectite",
    "Medichamite",
    "Meganiumite",
    "Meowsticite",
    "Pidgeotite",
    "Pinsirite",
    "Sablenite",
    "Scizorite",
    "Scovillainite",
    "Sharpedonite",
    "Skarmorite",
    "Slowbronite",
    "Starminite",
    "Steelixite",
    "Tyranitarite",
    "Venusaurite",
    "Victreebelite",
    "Aspear Berry",
    "Babiri Berry",
    "Charti Berry",
    "Cheri Berry",
    "Chesto Berry",
    "Chilan Berry",
    "Chople Berry",
    "Coba Berry",
    "Colbur Berry",
    "Haban Berry",
    "Kasib Berry",
    "Kebia Berry",
    "Leppa Berry",
    "Lum Berry",
    "Occa Berry",
    "Oran Berry",
    "Passho Berry",
    "Payapa Berry",
    "Pecha Berry",
    "Persim Berry",
    "Rawst Berry",
    "Rindo Berry",
    "Roseli Berry",
    "Shuca Berry",
    "Sitrus Berry",
    "Tanga Berry",
    "Wacan Berry",
    "Yache Berry",
)

MEGA_STONE_TO_BASE_SPECIES = {
    "Abomasite": ("Abomasnow",),
    "Absolite": ("Absol",),
    "Aerodactylite": ("Aerodactyl",),
    "Aggronite": ("Aggron",),
    "Alakazite": ("Alakazam",),
    "Altarianite": ("Altaria",),
    "Ampharosite": ("Ampharos",),
    "Audinite": ("Audino",),
    "Banettite": ("Banette",),
    "Beedrillite": ("Beedrill",),
    "Blastoisinite": ("Blastoise",),
    "Cameruptite": ("Camerupt",),
    "Chandelurite": ("Chandelure",),
    "Charizardite X": ("Charizard",),
    "Charizardite Y": ("Charizard",),
    "Chesnaughtite": ("Chesnaught",),
    "Chimechite": ("Chimecho",),
    "Clefablite": ("Clefable",),
    "Crabominite": ("Crabominable",),
    "Delphoxite": ("Delphox",),
    "Dragoninite": ("Dragonite",),
    "Drampanite": ("Drampa",),
    "Emboarite": ("Emboar",),
    "Excadrite": ("Excadrill",),
    "Feraligite": ("Feraligatr",),
    "Floettite": ("Eternal Flower Floette",),
    "Froslassite": ("Froslass",),
    "Galladite": ("Gallade",),
    "Garchompite": ("Garchomp",),
    "Gardevoirite": ("Gardevoir",),
    "Gengarite": ("Gengar",),
    "Glalitite": ("Glalie",),
    "Glimmoranite": ("Glimmora",),
    "Golurkite": ("Golurk",),
    "Greninjite": ("Greninja",),
    "Gyaradosite": ("Gyarados",),
    "Hawluchanite": ("Hawlucha",),
    "Heracronite": ("Heracross",),
    "Houndoominite": ("Houndoom",),
    "Kangaskhanite": ("Kangaskhan",),
    "Lopunnite": ("Lopunny",),
    "Lucarionite": ("Lucario",),
    "Manectite": ("Manectric",),
    "Medichamite": ("Medicham",),
    "Meganiumite": ("Meganium",),
    "Meowsticite": ("Meowstic (Male)", "Meowstic (Female)"),
    "Pidgeotite": ("Pidgeot",),
    "Pinsirite": ("Pinsir",),
    "Sablenite": ("Sableye",),
    "Scizorite": ("Scizor",),
    "Scovillainite": ("Scovillain",),
    "Sharpedonite": ("Sharpedo",),
    "Skarmorite": ("Skarmory",),
    "Slowbronite": ("Slowbro",),
    "Starminite": ("Starmie",),
    "Steelixite": ("Steelix",),
    "Tyranitarite": ("Tyranitar",),
    "Venusaurite": ("Venusaur",),
    "Victreebelite": ("Victreebel",),
}